version: "3.4"

services:
  db:
    image: postgres:15-alpine
    container_name: mutual-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  apidev:
    container_name: mutual-api-development
    build:
      context: .
      target: development
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: "pnpm run dev:container"
    depends_on: 
      - db
    # command: tail -f /dev/null
