# fly.toml app configuration file generated for staging-log-shipper on 2024-01-07T23:18:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "staging-log-shipper"
primary_region = "dfw"

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[env]
  SUBJECT = "logs.*mutual-supply.>"

[[services]]
  http_checks = []
  internal_port = 8686

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
