name: Deploy Logs
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'packages/server/fly.staging.logs.toml'
jobs:
  deploy:
    name: Deploy logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with: 
          version: '0.1.135'
      - name: Deploy
        working-directory: packages/server
        run: ./deploy-logs.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_LOGGING }}
